//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logs
    {
        public System.DateTime dateTime { get; set; }
        public string LogText { get; set; }
        public int IdLog { get; set; }
    }
}
